function [ bankid chanid ] = nlFT_parseFTName( chanlabel )

% function [ bankid chanid ] = nlFT_parseFTName( chanlabel )
%
% This parses a name generated by nlFT_makeFTName, turning the compound name
% back into bank and channel IDs.


bankid = 'bogus';
chanid = NaN;

alltokens = regexp( chanlabel, '^\s*(\S+)_(\d+)$', 'tokens' );

% With one input string, indexing is alltokens{matchnum}{tokennum}.

if isempty(alltokens)
  disp(sprintf( '###  Couldn''t parse channel label "%s".', chanlabel ));
else
  bankid = alltokens{1}{1};
  chanid = str2num(alltokens{1}{2});
end


% Done.

end


%
% This is the end of the file.
