function [All_Trials_Data_Match_Norm_Mean,...
    All_Trials_Data_NotMatch_Norm_Mean,...
    All_Trials_Baseline_Match_Norm_Mean,...
    All_Trials_Baseline_NotMatch_Norm_Mean,...
    All_Trials_Data_Match_Norm_STD_ERROR,...
    All_Trials_Data_NotMatch_Norm_STD_ERROR,...
    All_Trials_Baseline_Match_Norm_STD_ERROR,...
    All_Trials_Baseline_NotMatch_Norm_STD_ERROR,...
    All_Time_Data,All_Time_Baseline] = cgg_procTrialNormalization(...
    Start_IDX,End_IDX,Start_IDX_Baseline,End_IDX_Baseline,...
    trial_file_name,trialData,TrialCondition,MatchValue,TrialCount,...
    TrialDuration_Minimum,Window_Before_Data,Window_After_Data,...
    Window_Before_Baseline,Window_After_Baseline)
%CGG_PROCTRIALNORMALIZATION Summary of this function goes here
%   Detailed explanation goes here



[All_Trials_Baseline,All_Trials_Data_Match,...
    All_Trials_Data_NotMatch,All_Trials_Baseline_Match,...
    All_Trials_Baseline_NotMatch,Trial_Counter_Match,...
    Trial_Counter_NotMatch] = cgg_getSeparateTrialsByCriteria(...
    Start_IDX,End_IDX,Start_IDX_Baseline,End_IDX_Baseline,...
    trial_file_name,trialData,TrialCondition,MatchValue,TrialCount,...
    TrialDuration_Minimum);


%%
All_Trials_Baseline_Mean=mean(All_Trials_Baseline,[2 3]);
All_Trials_Baseline_STD=std(All_Trials_Baseline,0,[2 3]);

All_Trials_Data_Match_Norm=(All_Trials_Data_Match-All_Trials_Baseline_Mean)./All_Trials_Baseline_STD;
All_Trials_Data_NotMatch_Norm=(All_Trials_Data_NotMatch-All_Trials_Baseline_Mean)./All_Trials_Baseline_STD;
All_Trials_Baseline_Match_Norm=(All_Trials_Baseline_Match-All_Trials_Baseline_Mean)./All_Trials_Baseline_STD;
All_Trials_Baseline_NotMatch_Norm=(All_Trials_Baseline_NotMatch-All_Trials_Baseline_Mean)./All_Trials_Baseline_STD;

All_Trials_Data_Match_Norm_Mean=mean(All_Trials_Data_Match_Norm,3);
All_Trials_Data_NotMatch_Norm_Mean=mean(All_Trials_Data_NotMatch_Norm,3);
All_Trials_Baseline_Match_Norm_Mean=mean(All_Trials_Baseline_Match_Norm,3);
All_Trials_Baseline_NotMatch_Norm_Mean=mean(All_Trials_Baseline_NotMatch_Norm,3);

All_Trials_Data_Match_Norm_STD_ERROR=std(All_Trials_Data_Match_Norm,0,3)/sqrt(Trial_Counter_Match);
All_Trials_Data_NotMatch_Norm_STD_ERROR=std(All_Trials_Data_NotMatch_Norm,0,3)/sqrt(Trial_Counter_NotMatch);
All_Trials_Baseline_Match_Norm_STD_ERROR=std(All_Trials_Baseline_Match_Norm,0,3)/sqrt(Trial_Counter_Match);
All_Trials_Baseline_NotMatch_Norm_STD_ERROR=std(All_Trials_Baseline_NotMatch_Norm,0,3)/sqrt(Trial_Counter_NotMatch);

All_Time_Data=linspace(-Window_Before_Data,...
    Window_After_Data,...
    length(All_Trials_Data_Match_Norm_Mean));
All_Time_Baseline=linspace(-Window_Before_Baseline,...
    Window_After_Baseline,...
    length(All_Trials_Baseline_Match_Norm_Mean));


end

