function [outputArg1,outputArg2] = cgg_runRankImportanceAnalysis(inputArg1,inputArg2)
%CGG_RUNRANKIMPORTANCEANALYSIS Summary of this function goes here
%   Detailed explanation goes here



[~,IA_Table_Average] = cgg_procSingleImportanceAnalysis(...
    cfg_Encoder,EpochDir,'MatchType',MatchType,'NumRemoved',1, ...
    'NumEntries',NumEntries, ...
    'maxworkerMiniBatchSize',maxworkerMiniBatchSize, ...
    'DataFormat',DataFormat,'IsQuaddle',IsQuaddle, ...
    'RemovalType','Channel','BaselineArea',BaselineArea, ...
    'BaselineChannel',BaselineChannel,'BaselineLatent',BaselineLatent, ...
    'WantDelay',WantDelay);





end

