function OutTable = cgg_getBlockAccuracyAdditionSimplified(InTable,...
    RemovedName,PresentName,NotPresentName,Accuracy,Window_Accuracy,...
    SessionIDX,Weighting)
%CGG_GETBLOCKACCURACYADDITIONSIMPLIFIED Summary of this function goes here
%   Detailed explanation goes here

OutTable = InTable;

RemovedIDX = strcmp(OutTable.("Removed Areas"){1}{:,"Area Names"},RemovedName);
PresentIDX = strcmp(OutTable.("Removed Areas"){1}{:,"Area Names"},PresentName);
NotPresentIDX = strcmp(OutTable.("Removed Areas"){1}{:,"Area Names"},NotPresentName);

OutTable = cgg_addBlockValueToTable(OutTable,"Removed Areas", ...
    RemovedIDX,"Accuracy",Accuracy);
OutTable = cgg_addBlockValueToTable(OutTable,"Removed Areas", ...
    RemovedIDX,"Window Accuracy",Window_Accuracy);
OutTable = cgg_addBlockValueToTable(OutTable,"Removed Areas", ...
    RemovedIDX,"Session Number",SessionIDX);
OutTable = cgg_addBlockValueToTable(OutTable,"Removed Areas", ...
    RemovedIDX,"Weight Table",Weighting);

OutTable = cgg_addBlockValueToTable(OutTable,"Present Areas", ...
    PresentIDX,"Accuracy",Accuracy);
OutTable = cgg_addBlockValueToTable(OutTable,"Present Areas", ...
    PresentIDX,"Window Accuracy",Window_Accuracy);
OutTable = cgg_addBlockValueToTable(OutTable,"Present Areas", ...
    PresentIDX,"Session Number",SessionIDX);
OutTable = cgg_addBlockValueToTable(OutTable,"Present Areas", ...
    PresentIDX,"Weight Table",Weighting);

OutTable = cgg_addBlockValueToTable(OutTable,"Not Present Areas", ...
    NotPresentIDX,"Accuracy",Accuracy);
OutTable = cgg_addBlockValueToTable(OutTable,"Not Present Areas", ...
    NotPresentIDX,"Window Accuracy",Window_Accuracy);
OutTable = cgg_addBlockValueToTable(OutTable,"Not Present Areas", ...
    NotPresentIDX,"Session Number",SessionIDX);
OutTable = cgg_addBlockValueToTable(OutTable,"Not Present Areas", ...
    NotPresentIDX,"Weight Table",Weighting);


end

